In [6]:
import numpy as np

In [4]:
#FUNCTION UTK CEK APAKAH MATRIKS DIAGONALLY DOMINANT

def isDiagonallyDominant(x):
    #Mengubah x menjadi np array sehingga bisa dilakukan operasi np lainnya
    x = np.array(x)

    #untuk mengambil nilai diagonalnya
    diag = np.diag(np.abs(x))

    #Menghitung jumlah elemen selain diagonalnya
    off_diag = np.sum(np.abs(x), axis = 1) - diag
    # np.sum(np.abs(x), axis = 1) - diag
    #   -> menjumlahkan nilai setiap baris - elemen yg masuk diagonalnya

    # Jika semua diagonal lebih besar dari off_diag maka return True
    if np.all(diag > off_diag):
        return True
    else:
        False

In [ ]:
# FUNCTION OPERASI GAUSS SEIDEL

def gaussSeidel(x, y, epsilon = 0.01, t = 15):
    #menerima parameter matris x dan y
    # epsilon --> nilai toleransi
    # t --> berapa kali iterasi maksimum

    # Memanggil fungsi diagonally Dominant utk cek
    # --> Jika tidak diagonally Dominant, operasi tdk bisa dilakukan
    if not isDiagonallyDominant(x):
        print("Matrice is not diagonally dominant")
        return
    
    # Mengubah x dan y menjadi numpy array
    x = np.array(x)
    y = np.array(y)

    # Mengambil diagonal dari matriks x
    diag = np.diag(x)

    # Mengubah semua nilai di matriks x menjadi (-)
    # --> karena utk mencari E akan dilakukan operasi pengurangan
    x = -x

    # Mengisi diagonal utama dengan 0
    np.fill_diagonal(x, 0)
    
    # Membuat array 1D untuk menampung nilai x1, x2, x3
    # semua nilai array diisi dengan 0 dan berbentuk identik dengan x baris ke 0 (1D)
    mtx_old = np.zeros(x[0].shape)

    # Looping untuk mengisi matriks
    for i in range(t):
        # Mengkopi nilai matriks lama ke matriks baru
        # mtx_new akan menyimpan nilai x1, x2, x3 hasil operasi loopingan ke sekian
        mtx_new = np.array(mtx_old)

        # looping sebanyak element dari x
        for idx, row in enumerate(x) :

            # Untuk mencari nilai x1, x2, x3
            # x1 = ( y1 - koefisien x2 - koefisien x3 ) / koefisien x1
            # koef x1 == diagonal
            mtx_new[idx] = (y[idx] + np.dot(row, mtx_new)) / diag[idx]

        #Print hasil nilai dari setiap iterasi
        print(f"Iterasi ke-{i+1} ")
        print(mtx_new)

        # Mencari nilai error dengan akar dari new - old kali new - old
        dx = np.sqrt(np.dot(mtx_new - mtx_old, mtx_new - mtx_old))
        print(f"Nilai dx: {dx}")

        #Selection agar berhenti jika misalkan dx sudah lebih kecil dari Epsilon
        if dx < epsilon :
            print("Konvergen")
            return
        
        # Mengubah nilai matriks lama menjadi matriks baru
        mtx_old = mtx_new

    # Matriks no solution
    print("Metode tidak konvergen")
    return

In [17]:
Xs = [
    [10, 4, 5],
    [1, 6, 3],
    [3, 1, 6]
]

Ys = [8, 5, 10]

gaussSeidel(Xs, Ys)

Iterasi ke-1 
[0.8  0.7  1.15]
Nilai dx: 1.5660459763365826
Iterasi ke-2 
[-0.055       0.2675      1.64958333]
Nilai dx: 1.0805853769806644
Iterasi ke-3 
[-0.13179167  0.03050694  1.72747801]
Nilai dx: 0.2610177177676033
Iterasi ke-4 
[-0.07594178 -0.01774871  1.70759568]
Nilai dx: 0.07644033428894105
Iterasi ke-5 
[-0.04669835 -0.01268145  1.69212942]
Nilai dx: 0.03346730224036309
Iterasi ke-6 
[-0.04099213 -0.00589935  1.68814596]
Nilai dx: 0.009717289357327349
Konvergen


In [22]:
Xs = [
    [4, 2, -1],
    [3, 9, 4],
    [2, 1, 4]
]

Ys = [5, 3, 8]

gaussSeidel(Xs, Ys)

Iterasi ke-1 
[ 1.25       -0.08333333  1.39583333]
Nilai dx: 1.8755786144251296
Iterasi ke-2 
[ 1.640625   -0.83391204  1.38816551]
Nilai dx: 0.846176740760796
Iterasi ke-3 
[ 2.0139974  -0.95496158  1.2317417 ]
Nilai dx: 0.42252614939212113
Iterasi ke-4 
[ 2.03541621 -0.89257949  1.20543677]
Nilai dx: 0.07100873265370698
Iterasi ke-5 
[ 1.99764894 -0.86829932  1.21825036]
Nilai dx: 0.04669135056307749
Iterasi ke-6 
[ 1.98871225 -0.87101535  1.22339771]
Nilai dx: 0.010664730338769926
Iterasi ke-7 
[ 1.99135711 -0.87418469  1.22286762]
Nilai dx: 0.004161841126395246
Konvergen


In [ ]:
XS = [
    [5, -3, 2],
    [4, 6, 3],
    [2, -1, 7]
]

YS = [7, 12, 9]

gaussSeidel(XS, YS)

Matrice is not diagonally dominant
